[package]
name = "pcotool"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.2", default-features = false, features = [ "http2", "json", "rustls-tls" ] }
tokio = { version = "1.37.0", features = [ "full" ] }
